/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PagamentoCartao;
import controller.PagamentoDinheiro;
import controller.RepositorioVenda;
import controller.Supermercado;
import controller.Venda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Item;
import model.Usuario;

/**
 *
 * @author kaio.teixeira
 */
public class Caixa extends JanelaPadrao {

    private String valorTotal;
    private ArrayList<Item> listFinal;
    private viewVenda pai;

    /**
     * Creates new form Caixa
     */
    public Caixa(String valor, ArrayList<Item> list, viewVenda tela) {
        initComponents();
        this.listFinal = list;
        this.valorTotal = valor;
        txtTotalCompra.setText(valorTotal);
        this.pai = tela;
        txtTroco.setEnabled(false);
        txtTotalCompra.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotalCompra = new javax.swing.JTextField();
        lblTotalCompra = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JTextField();
        lblValorRecebido = new javax.swing.JLabel();
        txtValorPendente = new javax.swing.JTextField();
        lblValorPendente = new javax.swing.JLabel();
        cmbTipoPagamento = new javax.swing.JComboBox<>();
        lblTroco = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        jVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtTotalCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCompraActionPerformed(evt);
            }
        });

        lblTotalCompra.setText("Total da Compra:");

        lblValorRecebido.setText("Valor Recebido:");

        txtValorPendente.setEditable(false);

        lblValorPendente.setText("Valor Pendente:");

        cmbTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de Crédito" }));
        cmbTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoPagamentoActionPerformed(evt);
            }
        });

        lblTroco.setText("Troco:");

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jVoltar.setText("Voltar");
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalCompra))
                    .addComponent(lblValorRecebido)
                    .addComponent(lblValorPendente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorPendente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalCompra))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTroco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPagar)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCompra)
                    .addComponent(cmbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorPendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorPendente))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorRecebido))
                .addGap(18, 18, 18)
                .addComponent(btnPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTroco)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVoltar))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed

        switch (cmbTipoPagamento.getSelectedIndex()) {
            case 0:

                PagamentoDinheiro pagamentoDinheiro = new PagamentoDinheiro();
                try {
                    pagamentoDinheiro.Pagamento(Float.parseFloat(txtValorPendente.getText()), Float.parseFloat(txtValorRecebido.getText()));
                } catch (NumberFormatException e) {
                    pagamentoDinheiro.Pagamento(Float.parseFloat(txtTotalCompra.getText()), Float.parseFloat(txtValorRecebido.getText()));
                } finally {
                    txtTroco.setText(String.valueOf(pagamentoDinheiro.getTroco()));
                    txtValorPendente.setText(String.valueOf(pagamentoDinheiro.getPagamentoPendente()));
                    Venda novaVenda = new Venda();
                    novaVenda.setItensVenda(listFinal);
                    novaVenda.setCaixa(Supermercado.getInstancia().getCadastro().getUsuarioLogado());
                    String data = new SimpleDateFormat("dd.MM.yyyy").format(new java.util.Date());
                    novaVenda.setData(data);
                    int idV = 1;
                    System.out.println(Supermercado.getInstancia().getVenda().getLista().size());
                    if (!Supermercado.getInstancia().getVenda().getLista().isEmpty()) {
                        idV = Supermercado.getInstancia().getVenda().getLista().size() + 1;
                    }

                    novaVenda.setIdVenda(idV);
                    try {
                        Supermercado.getInstancia().getVenda().inserir(novaVenda);
//                        RepositorioVenda.obterInstancia().inserir(novaVenda);
                        System.out.println(Supermercado.getInstancia().getVenda().getLista().size());
//                        RepositorioVenda rv = RepositorioVenda.obterInstancia();
//                        Supermercado.getInstancia().setVenda(rv);
                        Supermercado.getInstancia().salvaSupermercado();
                    } catch (Exception ex) {
                        Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                break;
            case 1:
                PagamentoCartao pagamentoCartao = new PagamentoCartao();
                txtValorRecebido.setText(txtTotalCompra.getText());
                Venda novaVenda = new Venda();
                novaVenda.setItensVenda(listFinal);
                novaVenda.setCaixa(Supermercado.getInstancia().getCadastro().getUsuarioLogado());
                String data = new Date().toString();
                novaVenda.setData(data);
                novaVenda.setIdVenda(Supermercado.getInstancia().getVenda().getLista().size());

                try {
                    RepositorioVenda.obterInstancia().inserir(novaVenda);
                    RepositorioVenda rv = RepositorioVenda.obterInstancia();
                    Supermercado.getInstancia().setVenda(rv);
                    Supermercado.getInstancia().salvaSupermercado();
                } catch (Exception ex) {
                    Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }


    }//GEN-LAST:event_btnPagarActionPerformed

    private void txtTotalCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCompraActionPerformed

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        this.dispose();
        this.pai.setVisible(true);
    }//GEN-LAST:event_jVoltarActionPerformed

    private void cmbTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPagamentoActionPerformed

        if (cmbTipoPagamento.getSelectedItem().equals("Dinheiro")) {
            txtValorPendente.setVisible(true);
            txtValorRecebido.setEnabled(true);
        } else {
            txtValorPendente.setVisible(false);
            txtTotalCompra.setEnabled(false);
            txtValorRecebido.setText(valorTotal);
            txtValorRecebido.setEnabled(false);
            btnPagar.setEnabled(true);
        }

    }//GEN-LAST:event_cmbTipoPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cmbTipoPagamento;
    private javax.swing.JButton jVoltar;
    private javax.swing.JLabel lblTotalCompra;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorPendente;
    private javax.swing.JLabel lblValorRecebido;
    private javax.swing.JTextField txtTotalCompra;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPendente;
    private javax.swing.JTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables
}
