/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Supermercado;
import controller.Venda;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Item;
import model.Produto;

/**
 *
 * @author visitante
 */
public class viewVenda extends javax.swing.JFrame {

    private Venda venda;

    private ArrayList<Item> list;

    /**
     * Creates new form viewVenda
     */
    public viewVenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        preencherComboProdutos();
        this.venda = new Venda();
        this.list = new ArrayList<Item>();
        DefaultTableModel model = (DefaultTableModel) jTableListVenda.getModel();
        model.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProdutos = new javax.swing.JComboBox<>();
        jTextQuantidade = new javax.swing.JTextField();
        jAdicionarProduto = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListVenda = new javax.swing.JTable();
        jValorTotal = new javax.swing.JTextField();
        jPagamento = new javax.swing.JButton();
        jremoveProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutosActionPerformed(evt);
            }
        });

        jAdicionarProduto.setText("Adicionar Produto");
        jAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdicionarProdutoActionPerformed(evt);
            }
        });

        jTableListVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Valor", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTableListVenda);

        jPagamento.setText("Finalizar Pagamento");
        jPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagamentoActionPerformed(evt);
            }
        });

        jremoveProd.setText("Remover Produto");
        jremoveProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremoveProdActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Total:");

        jLabel2.setText("Produto:");

        jLabel3.setText("Quantidade");

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPagamento))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jremoveProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProdutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAdicionarProduto)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addComponent(jAdicionarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jremoveProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPagamento)
                    .addComponent(jCancelar))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProdutosActionPerformed

    private void jAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarProdutoActionPerformed
        int id = acharId((String) jProdutos.getSelectedItem(), Supermercado.getInstancia().getEstoque().getItens());
        String idsString = id + "";
        int auxQuantidade = Integer.parseInt(jTextQuantidade.getText());

        if (this.venda.registraItem(idsString, auxQuantidade)) {
            DefaultTableModel model = (DefaultTableModel) jTableListVenda.getModel();
            Produto produto = Supermercado.getInstancia().getEstoque().getItens().get(idsString).getProduto();
            Object[] obj = {produto.getNomeProduto(), produto.getPreco(), auxQuantidade};
            model.insertRow(model.getRowCount(), obj);
            Item item = new Item(produto, Integer.parseInt(jTextQuantidade.getText()));
            this.list.add(item);
            jTextQuantidade.setText("");
            jValorTotal.setText(calculaValorTotal() + "");
            System.out.println(Supermercado.getInstancia().getEstoque().getItens().get(idsString).getQuantidade());
        }
    }//GEN-LAST:event_jAdicionarProdutoActionPerformed

    private void jPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagamentoActionPerformed
        Caixa novoCaixa = new Caixa(jValorTotal.getText(),this.list,this);
        novoCaixa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPagamentoActionPerformed

    private void jremoveProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremoveProdActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableListVenda.getModel();
        int id = acharId((String) jProdutos.getSelectedItem(), Supermercado.getInstancia().getEstoque().getItens());
        String idsString = id + "";
        int quantidade = (int) model.getValueAt(jTableListVenda.getSelectedRow(), 2);
        list.remove(jTableListVenda.getSelectedRow());
        model.removeRow(jTableListVenda.getSelectedRow());
        jValorTotal.setText(calculaValorTotal() + "");
        this.venda.removeItem(idsString, quantidade);
    }//GEN-LAST:event_jremoveProdActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableListVenda.getModel();

        while (model.getRowCount() != 0) {
            int id = acharId((String) jProdutos.getSelectedItem(), Supermercado.getInstancia().getEstoque().getItens());
            String idsString = id + "";
            String quantidade =  (String) model.getValueAt(jTableListVenda.getSelectedRow(), 2);
            list.remove(jTableListVenda.getSelectedRow());
            model.removeRow(jTableListVenda.getSelectedRow());
            jValorTotal.setText(calculaValorTotal() + "");
            this.venda.removeItem(idsString, Integer.parseInt(quantidade));  
        }
    }//GEN-LAST:event_jCancelarActionPerformed
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jAdicionarProduto;
    private javax.swing.JButton jCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jPagamento;
    private javax.swing.JComboBox<String> jProdutos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListVenda;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JTextField jValorTotal;
    private javax.swing.JButton jremoveProd;
    // End of variables declaration//GEN-END:variables

    private void preencherComboProdutos() {
        jProdutos.removeAllItems();
        Map<String, Item> itens = Supermercado.getInstancia().getEstoque().getItens();
        Set<String> keys = itens.keySet();
        TreeSet<String> sortedKeys = new TreeSet<String>(keys);
        for (String key : sortedKeys) {
            Item item = itens.get(key);
            jProdutos.addItem(item.getProduto().getNomeProduto());

        }
    }

    private int acharId(String nome, Map<String, Item> itens) {
        Set<String> keys = itens.keySet();
        TreeSet<String> sortedKeys = new TreeSet<String>(keys);
        for (String key : sortedKeys) {
            String nomeatual = itens.get(key).getProduto().getNomeProduto();
            if (nomeatual.equals(nome)) {
                return Integer.parseInt(key);
            }
        }
        return -1;
    }

    public float calculaValorTotal() {
        float calculoTotal = 0;

        for (int i = 0; i < this.list.size(); i++) {
            float valorTotalItem = (this.list.get(i).getQuantidade() * this.list.get(i).getProduto().getPreco());
            calculoTotal += valorTotalItem;
        }
        return calculoTotal;
    }
}
